name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123456"
          envkey_POSTGRES_DB: "traveler_test"
          envkey_DATABASE_URL: "postgres://postgres:123456@db:5432/traveler_test"
          envkey_SECRET_CRYPTR: "icsfuangfcyu"
          envkey_SECRET_JWT: "gsagdsggfdsfgs"
          envkey_CLERK_API_KEY: "test_VKJ04MKRzgahxtVWszJEyxyOff5uhnqlu9"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app
      - name: Build
        run: npm i && npm run build
